stages:
  - test
  - deploy
  - publish

image: node:8.4.0

# Start the jobs
test_lints_sass:
  stage: test
  before_script:
    - npm install
  script:
    - npx grunt sasslint

test_lints_js:
  stage: test
  before_script:
    - npm install
  script:
    - npx grunt eslint

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
  environment:
    name: production
  artifacts:
    paths:
      - public
  only:
    - master
