stages:
  - deploy
  - publish

deploy_wip:
  stage: deploy
  image: ruby:latest
  environment:
    name: development
    url: https://eos-icons.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=eos-icons --api-key=$HEROKU_DEMO_PAGE_KEY
  only:
    - ops/deploy-dual-demo-pages
    - WIP-cherry

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/css dist/index.html dist/fonts dist/images/ .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
    - ops/deploy-dual-demo-pages

npm-publish:
  image: node:8
  stage: publish
  script:
    - npm install
    - npx semantic-release
  only:
    - master
