stages:
  - deploy
  - publish

image: node:8.4.0

deploy_wip:
  stage: deploy
  image: ruby:latest
  environment:
    name: development
    url: https://eos-icons.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=eos-icons --api-key=$HEROKU_DEMO_PAGE_KEY
  only:
    - new_branch_name_here

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
  environment:
    name: production
  artifacts:
    paths:
      - public

npm-publish:
  stage: publish
  script:
    - npm install
    - npx semantic-release
  only:
    - master
