stages:
  - test
  - deploy
  - publish

image: node:8.4.0
# Common script to all jobs
before_script:
  - npm install

# Lets cache the npm install per stages in the current branch
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
  - node_modules/
  - vendors/node_modules/

# Start the jobs
test_lints_sass:
  stage: test
  script:
    - npm run test:sass

test_lints_js:
  stage: test
  script:
    - npm run test:js

test_lints_pug:
  stage: test
  script:
    - npm run test:pug

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r dist/* .public
    - mv .public public
  environment:
    name: production
  artifacts:
    paths:
      - public
  only:
    - master
