pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r dist/index.html dist/fonts templates/logo.png .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - version.1.0.0.WIP
